# Define flag replacement mappings
FLAG_REPLACEMENTS = {
    "cro": "hr",
    "ger": "de",
    "slo": "si",
    "uru": "uy",
    "chi": "cl",
    "gre": "gr",
    "sui": "ch",
    "den": "dk",
    "bul": "bg",
    "por": "pt",
    "tpe": "tw",
    "ned": "nl",
    "rsa": "za",
    "mon": "mc",
    "par": "py",
    "lat": "lv",
    "zim": "zw",
    "phi": "ph",
    "crc": "cr",
    "bar": "bb",
    "ber": "bm",
    "ngr": "ng",
    "hai": "ht",
    "esa": "sv",
    # Add more as needed
    # "xxx": "yy",
}